'use client';
import { motion } from 'framer-motion';
import { Sigma, Square, Hash } from 'lucide-react';
import { useTranslations } from 'next-intl';
const THEOREMS = [
  { id:'completing', icon:Square, title:'Completing the Square (The Method of al-Jabr)', attribution:'al-Khwārizmī, al-Jabr wa-al-Muqābala (c. 820 CE)', statement:'Any quadratic equation of the form x² + bx = c can be solved by completing the square: add (b/2)² to both sides, then take the square root.', setup:[{type:'text',value:'Let '},{type:'var',value:'x² + bx = c'},{type:'text',value:'. Al-Khwārizmī stated:'}], equation:'x² + bx + (b/2)²  =  c + (b/2)²     ⇒     x  =  √(c + (b/2)²)  −  b/2', note:'This is the method that gives algebra its name. "Al-Jabr" means "completion" — the act of adding (b/2)² to both sides to "complete" the square. Every algebra student in the world learns this method. It was stated in 820 CE — 771 years before Vieta formalized symbolic algebra (1591).', outcome:'The method that gave algebra its name. 771 years before European symbolic algebra.' },
  { id:'quadratic', icon:Sigma, title:'The Quadratic Formula', attribution:'al-Khwārizmī, al-Jabr wa-al-Muqābala (c. 820 CE)', statement:'The general solution to ax² + bx + c = 0, derived by completing the square — stated geometrically by al-Khwārizmī and algebraically by his successors.', setup:[{type:'text',value:'Let '},{type:'var',value:'a, b, c'},{type:'text',value:' be coefficients. Then:'}], equation:'x  =  ( −b  ±  √(b²  −  4ac) )  /  2a', note:'Al-Khwārizmī did not write the formula in modern notation (symbolic algebra did not exist yet). But he derived it geometrically — proving that the solution to any quadratic can be found by his method of completing the square. The formula itself is a direct algebraic translation of his geometric proof. Every high school student in the world learns it. It was derived 771 years before Vieta.', outcome:'The quadratic formula — derived geometrically. 771 years before European formalization.' },
  { id:'numerals', icon:Hash, title:'The Hindu-Arabic Numeral System (0–9 and Place Value)', attribution:'al-Khwārizmī, Kitāb al-Jāmiʿ wa-al-Tafrīq bi-Ḥisāb al-Hind (c. 825 CE)', statement:'The positional decimal system with zero — which replaced Roman numerals across the entire world — was introduced to the Islamic world by al-Khwārizmī and to Europe through his Latin translation.', setup:[{type:'text',value:'Let each digit '},{type:'var',value:'d'},{type:'text',value:' ∈ {0,1,2,...,9} have a value depending on its position:'}], equation:'N  =  dₙ×10ⁿ + dₙ₋₁×10ⁿ⁻¹ + ... + d₁×10 + d₀      (with 0 as placeholder)', note:'Al-Khwārizmī\'s book on Hindu calculation (c. 825 CE) introduced the decimal system with zero to the Islamic world. The Latin translation (12th c., titled "Algoritmi de numero Indorum") introduced it to Europe. The word "algorithm" comes from the Latin title — "Algoritmi" (his name) + "de numero Indorum" (on Indian numbers). Fibonacci\'s Liber Abaci (1202) spread it further. Every number you have ever written uses this system.', outcome:'The number system used by every computer on Earth. 380+ years before Fibonacci brought it to Europe.' },
];
export default function AlgMathematicalProofSection() {
  const tSections = useTranslations('Sections');
  return (
    <section id="math" className="relative min-h-screen flex flex-col items-center justify-center px-6 py-24 overflow-hidden">
      <div className="absolute inset-0 opacity-[0.025] pointer-events-none" style={{ backgroundImage: 'linear-gradient(rgba(212,175,55,1) 1px, transparent 1px), linear-gradient(90deg, rgba(212,175,55,1) 1px, transparent 1px)', backgroundSize: '60px 60px' }} />
      <div className="max-w-5xl w-full relative z-10">
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "0px 0px 15% 0px" }} transition={{ duration: 0.8 }} className="text-center mb-14">
          <p className="text-[10px] font-mono tracking-[0.4em] uppercase text-gold/70 mb-4 flex items-center justify-center gap-2"><Sigma className="w-3 h-3" />{tSections('MathematicalProof.chapterTitle')}</p>
          <h2 className="font-display text-4xl sm:text-6xl md:text-7xl text-cream leading-tight">Three theorems.<br /><span className="text-gradient-gold italic">All named after him.</span></h2>
          <p className="mt-6 text-cream-dim max-w-2xl mx-auto text-sm sm:text-base leading-relaxed">No other SDAM case has this: the discipline&apos;s name, the method&apos;s name, and the number system&apos;s origin all trace to one person. <span className="text-gold">Algebra</span> = his book. <span className="text-gold">Algorithm</span> = his name. <span className="text-gold">Arabic numerals</span> = his transmission. The mathematical content is equally original.</p>
        </motion.div>
        <div className="space-y-6">
          {THEOREMS.map((th, i) => {
            const Icon = th.icon;
            return (
              <motion.div key={th.id} initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "0px 0px 15% 0px" }} transition={{ duration: 0.7, delay: i * 0.1 }} className="glass-card-gold rounded-2xl overflow-hidden">
                <div className="flex items-center gap-4 p-5 sm:p-6 border-b border-gold/15"><div className="w-12 h-12 rounded-full bg-gold/10 border border-gold/30 flex items-center justify-center flex-shrink-0"><Icon className="w-6 h-6 text-gold" /></div><div className="flex-1 min-w-0"><p className="text-[10px] font-mono uppercase tracking-widest text-gold/70 mb-1">Theorem {String.fromCharCode(8544 + i)} · {th.attribution}</p><h3 className="font-display text-xl sm:text-2xl text-cream leading-tight">{th.title}</h3></div></div>
                <div className="p-5 sm:p-7 space-y-5">
                  <div><p className="text-[10px] font-mono uppercase tracking-widest text-cream-dim mb-2">Statement</p><p className="text-cream text-base sm:text-lg leading-relaxed italic font-display">&ldquo;{th.statement}&rdquo;</p></div>
                  <div><p className="text-[10px] font-mono uppercase tracking-widest text-cream-dim mb-2">Setup</p><p className="text-cream/85 text-sm sm:text-base leading-relaxed">{th.setup.map((part, j) => { if (part.type === 'var') return <span key={j} className="font-mono text-gold font-semibold px-1">{part.value}</span>; return <span key={j}>{part.value}</span>; })}</p></div>
                  <div className="relative"><p className="text-[10px] font-mono uppercase tracking-widest text-cream-dim mb-2">Theorem</p><div className="relative bg-cosmos-deep/60 border border-gold/25 rounded-xl py-6 px-4 sm:px-8 text-center overflow-hidden"><span className="absolute top-1 left-1 w-3 h-3 border-t border-l border-gold/50" /><span className="absolute top-1 right-1 w-3 h-3 border-t border-r border-gold/50" /><span className="absolute bottom-1 left-1 w-3 h-3 border-b border-l border-gold/50" /><span className="absolute bottom-1 right-1 w-3 h-3 border-b border-r border-gold/50" /><p className="font-mono text-sm sm:text-base md:text-lg text-gold-bright tracking-wide break-words">{th.equation}</p></div></div>
                  <div className="grid sm:grid-cols-2 gap-4 pt-2"><div className="border-l-2 border-gold/30 pl-3"><p className="text-[10px] font-mono uppercase tracking-widest text-gold/70 mb-1">Why it matters</p><p className="text-cream-dim text-xs sm:text-sm leading-relaxed">{th.note}</p></div><div className="border-l-2 border-gold/60 pl-3"><p className="text-[10px] font-mono uppercase tracking-widest text-gold mb-1">Result</p><p className="text-cream text-xs sm:text-sm leading-relaxed font-medium">{th.outcome}</p></div></div>
                </div>
              </motion.div>
            );
          })}
        </div>
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "0px 0px 15% 0px" }} transition={{ duration: 0.7, delay: 0.4 }} className="mt-12 text-center max-w-3xl mx-auto"><p className="text-cream/90 text-sm sm:text-base leading-relaxed">Fibonacci, Cardano, Vieta, and Turing were all brilliant. But the systematic method, the quadratic formula, and the number system they used were all in writing — in Arabic — 382–771 years earlier. The word &ldquo;algorithm&rdquo; is his name. SDAM treats this as <span className="text-gold">Tier-1 primary evidence — the only case where the proof IS the name.</span></p></motion.div>
      </div>
    </section>
  );
}
